[package]
name = "toram-online-auto-build-calculator"
version = "0.5.0"
description = "Toram Online auto build calculator"
authors = ["Toram Auto Building contributors"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
